### PR TITLE
feat: Add addCheqdQueryClient

### PR DESCRIPTION
**Pull request by DaevMithran**
Signed-off-by: DaevMithran <daevmithran1999@gmail.com>

### CODE REVIEW

**Comment by ankurdotb** [comment]
@DaevMithran FYI for the future, if you ever need to retarget a PR to different branch, you can just use the Edit at the top and retarget to a different base branch. :) (What I'd said earlier on splitting PRs was so that you could _immediately_ merge one PR to develop so that you didn't have to wait for review, and use a separate PR to main for the official release.)

Anyway, I rebase this using develop and there are tests failing. Can you please look?

**Comment by DaevMithran** [comment]
@Eengineer1 the tests are failing because of a circular dependency import. 
[reference link](https://stackoverflow.com/questions/37312197/node-js-v6-2-0-class-extends-is-not-a-function-error/37312355#37312355) 

If I move all the extensions in _.ts everything works fine. Should I do that or any better way?

**Comment by DaevMithran** [comment]
@Eengineer1 the tests throw an `Class extends value undefined is not a constructor or null`. As far as I know this issue is related to circular dependency etc

If I move the setUpResourcesExtension funciton inside _.ts the tests are passing successfully. Any suggestions on this issue?

**Comment by ankurdotb** [comment]
@DaevMithran Your tests seem to be failing

**Comment by ankurdotb** [comment]
Task linked: [DEV-1837 Implement cheqd queryclient feature in our sdk](https://app.clickup.com/t/6600954/DEV-1837)

**Pull request closed without merging**
