### PR TITLE
docs(readme): Marked resource support as completed 

### PR DESCRIPTION
**Pull request by rosspower11**

### CODE REVIEW

**Comment by rosspower11** [comment]
@Eengineer1  - updating readme for Resources completion. Pls could you review and merge

**Review by Eengineer1 — APPROVED** [review]
Approved, thanks!
BTW, removed `--runInBands` from test pipelines, since there were race conditions on sequence increment.

**Comment by askolesov** [comment]
`--runInBands` **is** exactly what prevents race conditions. From help:
ss9

So I would restore it.

**Comment by askolesov** [comment]
@Eengineer1 ^

**Comment by Eengineer1** [comment]
@askolesov I'm aware.
That's practically not the case though, if you check the initial [workflow run](https://github.com/cheqd/sdk/runs/8211405704?check_suite_focus=true) with the flag enabled.

A better solution would be to max out the workers to 1, along with `--runInBand` or add longer timeout interval.

**Comment by askolesov** [comment]
> That's practically not the case though, if you check the initial [workflow run](https://github.com/cheqd/sdk/runs/8211405704?check_suite_focus=true) with the flag enabled.

My guess is there is an interval between tx is committed and query server return updated data. Not sure, need to check.

> A better solution would be to max out the workers to 1, along with --runInBand or add longer timeout interval.

Indeed, there is a flag `-w, --maxWorkers`. Didn't see previously. This time was more lucky :)

So yep, let's use either `--maxWorkers` or `--runInBand`. Even if it doesn't eliminate racing condition completely, it will should frequency imo.

**Pull request merged**
